[project]
name = "inventory-challenge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dbt>=1.0.0.40.5",
    "dbt-bigquery>=1.10.0",
    "dbt-core>=1.10.4",
]
